In [1]:
%pylab inline

plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['font.size'] = 14.0

Populating the interactive namespace from numpy and matplotlib


In [2]:
import math_biol as mb

In [158]:
def Preys(y, S):
    (nPreds, nPreys) = S.shape
    return y[:,0:nPreys]

def Preds(y, S):
    (nPreds, nPreys) = S.shape
    return y[:,nPreys:]

def V(y, S):
    return np.dot(S, np.transpose(Preys(y,S)))

def C(y, S, g, H): # TODO: test this
    return  g * np.dot(np.diag(Preds(y,S)), V(y,S)) / (V(y,S) + H)
    

def rosmac(y, t, A, S, e, g, l, r, H, K, f):
    (nPreds, nPreys) = S.shape
    
    #Preys = lambda y: y[:,0:nPreys-1]
    #Preds = lambda y: y[:,nPreys:]
    
    
    #V = lambda y: np.dot(S, Preys(y))
    #C = lambda y: g * np.dot(np.diag(Preds(y),0), V(y)) / (V(y) + H)
    dydt = np.zeros((nPreys+nPreds, 1))
    
    a1 = r * np.diag(Preys(y,S)[0])
    a2 = (K - np.dot(A, np.transpose(Preys(y,S)))) / K
    dydt[0:nPreys, 0] = np.ravel(np.dot(a1, a2))
    
    #dydt[0:nPreys, 0] = np.dot((r * np.diag(Preys(y,S)[0])), (K - np.dot(A, np.transpose(Preys(y,S))))) / K
    #dydt[0:nPreys, 0] += - np.dot(np.dot(np.diag(Preys(y,S)), np.transpose(S)), C(y,g,H)/V(y,S))
    #dydt[0:nPreys, 0] += f
    
    dydt[nPreys:, 1] = e * C(y,S,g,H) - l * Preds(y,S)
    
    
    #V = @(y) S*Prey(y);
    #C = @(y) g.*diag(Pred(y))*V(y)./(V(y) + H);
    
    
    #dydt(1:nPreys, 1) = (r.*diag(Prey(y)))*(K - A*Prey(y))./K - diag(Prey(y))*S'*(C(y)./V(y)) + f;
    #dydt(nPreys+1:nPreys+nPreds, 1) = e.*C(y) - l.*Pred(y);
    
    return dydt

In [159]:
nPreys = 3
nPreds = 2

A = np.random.rand(nPreys, nPreys)
S = np.random.rand(nPreds, nPreys)

settings = {
    'A':A,
    'S':S,
    'e':1,
    'g':1,
    'l':1,
    'r':1,
    'H':1,
    'K':1,
    'f':0
}

def my_rosmac(y, t):
    return rosmac(y, t, **settings)

In [160]:
y_test = np.random.rand(1, nPreys+nPreds)

In [161]:
print(y_test)

[[ 0.40772614  0.72120476  0.09904686  0.4095956   0.35754086]]


In [162]:
Preys(y_test, S)

array([[ 0.40772614,  0.72120476,  0.09904686]])

In [163]:
V(y_test,S) / (V(y_test,S) + 1)

array([[ 0.40005247],
       [ 0.41381531]])

In [164]:
my_rosmac(y_test, 0)

ValueError: shapes (1,) and (2,1) not aligned: 1 (dim 0) != 2 (dim 0)

In [146]:
a1 = (1 * np.diag(Preys(y_test,S)[0]))
a2 = 1 - np.dot(A, np.transpose(Preys(y_test,S)))
np.dot(a1, a2)

array([[ 0.02213675],
       [ 0.09563098],
       [ 0.42300736]])

In [148]:
y_zeros = np.zeros((nPreys+nPreds, 1))
print(y_zeros)

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [150]:
y_zeros[1:3, 0]

array([ 0.,  0.])